# Docker Compose definition for easy development environment setup
# @I Document nginx proxy requirement for docker-compose development environment
version: '2'

services:

  # Where the main development happens.
  development:
    # Build.
    build:
      context: ./docker
      dockerfile: Dockerfile-go
    image: ms_development

    # Run.
    command: sleep infinity
    container_name: ms_development

    # Configure.
    environment:
      - VIRTUAL_HOST=api.mantis-shrimp.localhost
      - VIRTUAL_PORT=8888
      - VIRTUAL_NETWORK=nginx-proxy

    links:
      - elasticsearch
      - redis
      - trigger_api:ms-trigger-api
      - action_api:ms-action-api

    networks:
      - proxy-tier

    volumes:
      - ../../../..:/go

  # Service that runs the Trigger API. To be used when developing a consumer.
  trigger_api:
    # Build.
    build:
      context: ./docker
      dockerfile: Dockerfile-go
    image: ms_trigger_api

    # Run.
    command: /go/bin/ms_trigger_api
    container_name: ms_trigger_api

    # Configure.
    links:
      - elasticsearch

    networks:
      - proxy-tier

    volumes:
      - ../../../..:/go

  # Service that runs the Action API. To be used when developing a consumer.
  action_api:
    # Build.
    build:
      context: ./docker
      dockerfile: Dockerfile-go
    image: ms_action_api

    # Run.
    command: /go/bin/ms_action_api
    container_name: ms_action_api

    # Configure.
    links:
      - redis

    networks:
      - proxy-tier

    volumes:
      - ../../../..:/go

  # Databases.
  elasticsearch:
    # Build.
    build:
      context: ./docker
      dockerfile: Dockerfile-elasticsearch

    image: ms_elasticsearch

    # Run.
    container_name: ms_elasticsearch

    # Configure.
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g

    # 2GB memory limit - otherwise elasticsearch will eat up all memory.
    # It will complain and not start if provided less.
    mem_limit: 2147483648

    networks:
      - proxy-tier

    volumes:
      - ${DOCKER_COMPOSE_VOLUMES_DIR}/src/go-mantis-shrimp/elasticsearch:/usr/share/elasticsearch/data

  redis:
    # Build.
    image: redis:alpine

    # Run.
    command: redis-server --appendonly yes

    container_name: ms_redis

    # Configure.
    mem_limit: 268435456

    networks:
      - proxy-tier

    volumes:
      - ${DOCKER_COMPOSE_VOLUMES_DIR}/src/go-mantis-shrimp/redis:/data

  # Development tools.
  kibana:
    # Build.
    build:
      context: ./docker
      dockerfile: Dockerfile-kibana

    image: ms_kibana

    # Run.
    container_name: ms_kibana

    # Configure.
    environment:
      - VIRTUAL_HOST=kibana.mantis-shrimp.localhost
      - VIRTUAL_PORT=5601
      - VIRTUAL_NETWORK=nginx-proxy

    links:
      - elasticsearch

    networks:
      - proxy-tier

networks:
  proxy-tier:
    external:
      name: nginx-proxy
